language: php
php:
  - 7.0
before_install:
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash
script: 
  - phpunit tests/UserTest.php
  - phpunit tests/LibraryTest.php
  - phing -f build.xml
sudo: required
services:
  - docker
